# Generated by Django 4.2 on 2023-04-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registar_Fname', models.CharField(max_length=50)),
                ('registar_Email', models.EmailField(max_length=254)),
                ('registar_Mobile', models.IntegerField(max_length=10)),
                ('registar_Dob', models.DateField()),
                ('registar_Password', models.CharField(max_length=250)),
                ('registar_ConfmPassword', models.CharField(max_length=250)),
            ],
        ),
    ]
