# Generated by Django 4.2 on 2023-04-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehivles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vahicle_Img', models.ImageField(default='', upload_to='media/image')),
                ('vahicle_Name', models.CharField(max_length=50)),
                ('vahicle_Availability', models.CharField(max_length=50)),
                ('vahicle_Price', models.CharField(max_length=20)),
                ('vahicle_Description', models.TextField()),
            ],
        ),
    ]
